### ISSUE TITLE
writexl not available for r v.3.5.1 

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#111]
cholera template @epiamsterdam trying to save cleaned data set, but appears to not be available on newest version release?

**Comment by zkamvar** [comment]
There may be several reasons for this: https://stackoverflow.com/a/25721890/2752888

I'm not exactly sure why she's getting the error. It might be because she was temporarily without internet or the server that she was trying timed out. In any case, the error message is misleading because it never says _why_ the package was not available.

**Comment by aspina7** [comment]
ah - will put it in FAQ
