### ISSUE TITLE
msf_dict: consider simpler way to have an overview of variable value options

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/sitrep#186]
clicking in to each one defeats the purpose of reading in a dictionary (should be able to have dictionary open and look things up while recoding). 

~~Also double check that the value options that are produced are correct (though this seems to be have been a one-time issue. ~~

From https://github.com/R4EPI/sitrep/issues/136#issuecomment-508496907

Need more information on this.

**Comment by aspina7** [comment]
Well the first iteration just had possible values spread over columns (but then there was a bunch of empty columns for a lot of variables. 
Just being able to see the possible values for each variable in one glance rather than clicking in for each one would be ideal. 
But its definitely not priority. And people will be reading in their own dictionaries mostly anyway.

**Comment by aspina7** [comment]
closing as the long vs wide versions are enough
