### ISSUE TITLE
No analysis of diagnosis of measles in VCS template

### ISSUE THREAD

**Issue by pbkeating** [R4EPI/sitrep#256]
After reviewing the VCS template, it seems that there is no chunk that analyses the diagnosis of measles. This is included as standard in the template but not analysed.

**Comment by pbkeating** [comment]
Could also look at age at which they were infected. Don't know if it would be interesting to see based on age -age they were infected how recently they had measles i.e. part of recent outbreak or historic. Thoughts?

**Comment by aspina7** [comment]
Seems relevant. Time since infection also seems logical if information available (and reliable) - which i would guess is quite rare given self reporting of symptoms that are aspecific. 
Guess its not always a measles vcs but user can adapt as appropriate. 
Will chuck it in,.... only a few extra lines of code anyway and easy enough for people to delete.

**Comment by aspina7** [comment]
@pbkeating .... I added this analysis in a previous iteration, but there does not seem to be a diagnosis of measles variable in the dictionary you sent me....
