### ISSUE TITLE
Write a walkthrough for the outbreak template

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#32]
It would be good to have walkthrough and an introduction for the outbreak report template in the wiki. We can then later take the text and put it on a dedicated website

**Comment by aspina7** [comment]
so @pbkeating has made a start to this. Couple things that would be useful but not sure how to do it and other points that will be addressed as we go along. cc @zkamvar 

- References to line numbers in scripts (is there a more effective way to do this, as will change as we update). Could always just describe sections in words/headings but in case there is a workaround. 
- Update the list of packages accordingly. 
- Sidebar edits: is there a way to make useful hyperlinks to subsections based on headings? (just for better overview rather than people having to read through everything!) 

@epiamsterdam would be good if you could look at this if it has enough info for at least the HQ epis to take an initial look at the templates (see [here ](https://github.com/R4EPI/sitrep/wiki/1)-Home))
