### ISSUE TITLE
Issues with installing from github

### ISSUE THREAD

**Issue by aspina7** [R4EPI/sitrep#35]
Walking through installing from github and he got a whole bunch of errors - starting with not being able to update packages. See below. 

Probs good to address next week before sending out to epis. 

He needed to reinstall the package colorspace and restart the R session and then it worked for colorspace. Then got same error for rlang, repeated above steps and then epireports loaded correctly but templates are still not there.... 
@dirkschumacher @zkamvar 
<img width="674" alt="epireports_loading" src="https://user-images.githubusercontent.com/18347047/51400942-8d5cbc80-1b41-11e9-8798-439639d9d747.PNG">

**Comment by zkamvar** [comment]
I suspect these installation errors may be coming from the default setting of R regarding saving and loading of workspaces. This would cause loaded packages to stay loaded even if you start RStudio in a supposedly clean session.

I **strongly recommend** go to the <kbd>Global Options</kbd> of RStudio and de-select "load .RData on startup" and set "Save workspace to .RData on exit" to "Never" [as illustrated in this forum post from Hadley](https://community.rstudio.com/t/first-line-of-every-r-script/799/12):

![RStudio global options window showing a setting optimal for reproducibility](https://community.rstudio.com/uploads/default/optimized/1X/bde0475899393c600719edd4724981a6e6f0715f_1_522x500.jpg)

**Comment by aspina7** [comment]
@pbkeating can you try please? 
Would this also solve the templates not showing up though @zkamvar?

**Comment by zkamvar** [comment]
> Would this also solve the templates not showing up though @zkamvar?

This is a bit more difficult to diagnose, I'm afraid. How do you mean the templates don't show up?
One thing to check is if the installed version is the same as the github version. What happens if you type `packageDescription("epireports")$GithubSHA1` in the R console?

**Comment by zkamvar** [comment]
Also, whose computer was this?

**Comment by aspina7** [comment]
The only templates that show up are called "github_document" and "untitled_document"  (I think) will need to wait and see what pat comes back with

**Comment by zkamvar** [comment]
> The only templates that show up are called "github_document" and "untitled_document" (I think) will need to wait and see what pat comes back with

That's a bit strange. If rmarkdown is installed on the computer, I think the first two should appear like so:

 - Package Vignette (HTML) {rmarkdown}
 - GitHub Document (Markdown) {rmarkdown}

(see https://bookdown.org/yihui/rmarkdown/document-templates.html)

![](https://bookdown.org/yihui/rmarkdown/images/templates-select.png)

**Comment by zkamvar** [comment]
Also, what happens if you use the following:

```r
rmarkdown::draft("outbreak.Rmd", template = "outbreak", package = "epireports")
```

**Comment by pbkeating** [comment]
Hi both,

Upon opening R this morning all the options for markdown templates were
available i.e mortality survey etc.
Maybe it just needed a restart?

@Zhian Kamvar <zkamvar@gmail.com>  you were right, the two templates
available previously were github document and package vignette

Thanks,
Pat

**Comment by pbkeating** [comment]
Ah. Was it your computer, Pat? Did you make the changes in the global options that I mentioned above?

**Comment by pbkeating** [comment]
Hi Zhian,

I didn't change anything. Just opened R today and everything was there.

Thanks,
Pat

**Comment by AmmerB** [comment]
Still have issue installing as 'update' 
`> devtools::install_github("R4EPI/sitrep")
Downloading GitHub repo R4EPI/sitrep@master
These packages have more recent versions available.
Which would you like to update?

1:   backports  (1.1.3  -> 1.1.4 ) [CRAN]
2:   data.table (1.12.0 -> 1.12.2) [CRAN]
3:   ggplot2    (3.1.0  -> 3.1.1 ) [CRAN]
4:   rlang      (0.3.2  -> 0.3.4 ) [CRAN]
5:   tinytex    (0.11   -> 0.12  ) [CRAN]
6:   xfun       (0.5    -> 0.6   ) [CRAN]
7:   CRAN packages only
8:   All
9:   None`

**Comment by zkamvar** [comment]
It’s asking if you want to update these packages. This is normal behavior. If you don’t want to update, you can select “None”. We can add this to the wiki if you would like.

**Comment by zkamvar** [comment]
Also, sorry, only the first part of the message showed up for me. I’ll take a look into this later.

**Comment by zkamvar** [comment]
You will want to make sure that you are starting from a clean R session as described in the wiki. What might be happening is that you had a package loaded that had backports also loaded.

**Comment by AmmerB** [comment]
Did restart R session, but didn't make a difference. Based on last error message: 

```
> devtools::install_github("R4EPI/sitrep")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’
```

I tried this: 
`install.packages("backports")`

```
> install.packages("backports")
Installing package into ‘x:/path/’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/backports_1.1.4.zip'
Content type 'application/zip' length 66186 bytes (64 KB)
downloaded 64 KB
```

Then retried installing 'epireports' using: 
`devtools::install_github("R4EPI/sitrep")`

Success, everything including all *.rmd templates are updated now. Not sure if this is a more common issue, but would be great if the final 'epireports' package installer would by default install 'backports', not even sure what it does and of which package it is a codependency, but otherwise it halts the installation.

**Comment by zkamvar** [comment]
I think I've found the problem, which is an understandable mistake. You used `devtools::install_github()` instead of [the recommended `remotes::install_github()`](https://github.com/R4EPI/sitrep/wiki/1\)-Getting-started#installing-the-package). Devtools has backports as a downstream dependency, but remotes has no external dependencies. When you used `devtools::install_github()`, 'backports' was loaded in the background, which causes problems with updating.

A couple of notes:

> Did restart R session, but didn't make a difference. Based on last error message:

When I mentioned a clean R session, I'm talking about [setting the recommended RStudio configuration](https://github.com/R4EPI/sitrep/wiki/1)-Getting-started#configuring-rstudio) to never load previous R sessions on startup, which is not the default.

> Not sure if this is a more common issue, but would be great if the final 'epireports' package installer would by default install 'backports', not even sure what it does and of which package it is a codependency, but otherwise it halts the installation.

This issue will not appear if users make sure their session is clean and install using `remotes::install_github()`, as explained in the Wiki. FWIW, I'm working on #68, which will enable users to avoid the remotes/devtools debacle.

```r
# install.packages("drat")
drat:::add("R4EPI/epicran")
install.packages("sitrep")
```
