### ISSUE TITLE
Generate complete directories for analyses

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/sitrep#45]
Just an idea, but in addition to a single markdown template we could also provide functionality that helps scaffolding a complete set of directories according to some best practice. 

E.g. `scaffold_weekly_sitrep(path = ".")` creates a set of directories, please a readme on how to organize data, do analyses and archive the reports.

**Comment by zkamvar** [comment]
I think this is the purpose of https://github.com/reconhub/reportfactory

**Comment by aspina7** [comment]
Yep super good idea. Another think that may be useful is that in, the rmd, the user defines current week at the top. And then cases from after that week are dropped from linelist-cleaned, and for attackrate and faceted mapping it can be stratified by week up to current week of interest. 
(Necessary because sitrep written for prev week therefore has cases from "future" weeks)
